import AppKit
import XCTest
@testable import MementoCapture

@MainActor
final class ClipboardCaptureTests: XCTestCase {
    private func makePasteboard() -> NSPasteboard {
        NSPasteboard(name: NSPasteboard.Name("test.memento.\(UUID().uuidString)"))
    }

    private func makeCapture(_ pasteboard: NSPasteboard) -> ClipboardCapture {
        let capture = ClipboardCapture(pasteboard: pasteboard)
        capture.isEnabled = true
        return capture
    }

    func testCapturesPlainTextWhenEnabled() {
        let pasteboard = makePasteboard()
        let capture = makeCapture(pasteboard)

        pasteboard.clearContents()
        pasteboard.setString("hello world", forType: .string)

        XCTAssertEqual(capture.getNewClipboardContent(), "hello world")
    }

    func testReturnsNilWhenDisabled() {
        let pasteboard = makePasteboard()
        let capture = ClipboardCapture(pasteboard: pasteboard)
        capture.isEnabled = false

        pasteboard.clearContents()
        pasteboard.setString("hello", forType: .string)

        XCTAssertNil(capture.getNewClipboardContent())
    }

    func testUnchangedPasteboardReturnsNilOnSecondCall() {
        let pasteboard = makePasteboard()
        let capture = makeCapture(pasteboard)

        pasteboard.clearContents()
        pasteboard.setString("once", forType: .string)

        XCTAssertEqual(capture.getNewClipboardContent(), "once")
        XCTAssertNil(capture.getNewClipboardContent())
    }

    func testSkipsConcealedContent() {
        let pasteboard = makePasteboard()
        let capture = makeCapture(pasteboard)

        pasteboard.declareTypes(
            [.string, NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")],
            owner: nil
        )
        pasteboard.setString("hunter2", forType: .string)

        XCTAssertNil(capture.getNewClipboardContent())
    }

    func testSkipsTransientContent() {
        let pasteboard = makePasteboard()
        let capture = makeCapture(pasteboard)

        pasteboard.declareTypes(
            [.string, NSPasteboard.PasteboardType("org.nspasteboard.TransientType")],
            owner: nil
        )
        pasteboard.setString("temp", forType: .string)

        XCTAssertNil(capture.getNewClipboardContent())
    }

    func testSkipsAutoGeneratedContent() {
        let pasteboard = makePasteboard()
        let capture = makeCapture(pasteboard)

        pasteboard.declareTypes(
            [.string, NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")],
            owner: nil
        )
        pasteboard.setString("generated", forType: .string)

        XCTAssertNil(capture.getNewClipboardContent())
    }

    func testConcealedContentDoesNotBlockNextPlainCopy() {
        let pasteboard = makePasteboard()
        let capture = makeCapture(pasteboard)

        pasteboard.declareTypes(
            [.string, NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")],
            owner: nil
        )
        pasteboard.setString("secret", forType: .string)
        XCTAssertNil(capture.getNewClipboardContent())

        pasteboard.clearContents()
        pasteboard.setString("normal again", forType: .string)
        XCTAssertEqual(capture.getNewClipboardContent(), "normal again")
    }
}
