import Foundation
import AppKit

/// Captures clipboard content (can be disabled in settings)
@MainActor
final class ClipboardCapture {

    static let shared = ClipboardCapture()

    /// Marker types from the nspasteboard.org de facto standard. Password
    /// managers set ConcealedType on copied secrets; transient/auto-generated
    /// content is never worth indexing.
    private static let sensitiveMarkerTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    private let pasteboard: NSPasteboard
    private var lastChangeCount: Int

    /// Enable/disable clipboard capture (controlled by Settings)
    var isEnabled: Bool = false

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    /// Get clipboard content if it changed since last check
    /// Returns nil if disabled, unchanged, or marked concealed/transient
    func getNewClipboardContent() -> String? {
        guard isEnabled else { return nil }

        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return nil }

        lastChangeCount = currentCount

        if let types = pasteboard.types,
           types.contains(where: { Self.sensitiveMarkerTypes.contains($0) }) {
            return nil
        }

        // Only capture text content
        guard let content = pasteboard.string(forType: .string) else { return nil }

        // Skip if too long (probably not useful text)
        guard content.count < 10000 else { return nil }

        // Skip if it looks like a file path or binary data
        if content.hasPrefix("/") && content.contains(".") && !content.contains(" ") {
            return nil
        }

        return content.trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
